### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by sabderemane** [jupyter/accessibility#47] opened 2021-05-21 16:09 UTC
Create a contribution guide to help people who want to add knowledge to the repo. 

I think it can be usefull for storing things in the best way or help the team to get all informations at the same point.

**Comment by pws1453** [comment] 2022-03-23 16:47
I'm going to try to work on this issue this weekend, I will report back if I have any questions/comments/concerns.

**Comment by pws1453** [comment] 2022-03-27 23:00
Hello! I've had some time to look at the repo and it's resources a bit more. I see there's a CONTRIBUTING that was added in https://github.com/jupyter/accessibility/pull/35, and a [read the docs](https://jupyter-accessibility.readthedocs.io/en/latest/README.html) page that has been setup for the group. Is the issue related to the contents of CONTRIBUTING.md, that we'd like the contribution guide to be elsewhere (maybe the rtd?), or some combination of the two?

**Comment by isabela-pf** [comment] 2022-03-29 05:57
Thanks for giving this issue some much needed attention, and good catch! I think your instinct about this being a combination of your two ideas is correct.

While a PR with a contributing.md was opened before this issue, it wasn't merged for a while so some of this is indeed already completed. From my perspective, it would fully resolve this issue to 
- Make sure the contributing guide appears somewhere in the read the docs page
- Review the contributing guide to make sure it still makes sense (I'm seeing that there haven't been any edits since the file was added, but I know some of the repo architecture has changed so I would appreciate a once-over if possible. @tonyfast would know more about this if you have more questions)
- (this one is optional!) Add or clean up anything that you think would be useful along the way

I'd be happy to review any PR that might get opened for this, so don't hesitate to @ me before or after for help!

**Comment by bay1877** [comment] 2022-03-30 16:32
Hi, I am a classmate with pws1453. I will be working toward this issue as well, in communication and alongside pws1453. Thanks!

**Comment by bay1877** [comment] 2022-04-06 00:31
Hi, I am making some progress with reviewing the docs and contribution guides. I am running into some questions though. Would you like to drop them here or is there a more preferred/easier communication method? @isabela-pf

**Comment by isabela-pf** [comment] 2022-04-06 03:32
@bay1877 hey there! Writing them on the issue works fine for me, but if it's easier/faster for you to talk it out we can schedule a call. I'm @isabela-pf on gitter if that helps.

**Comment by bay1877** [comment] 2022-04-06 23:42
Okay, I don't mind posting them here. I will try my best to explain what questions I have so far. Before that, I can confirm that the existing CONTRIBUTION.md guide does already appear in the read the docs. Once I got to investigating the read the docs, I noticed that it was in need of some work too. Most of my work up to this point has been cleaning up the docs and organization in general rather than the contribution guide directly. My questions so far are the below.

1. I think it would be beneficial to clarify contributions directed toward accessibility issues on other jupyter projects vs contributions directed toward jupyter/accessibility. What are thoughts on that? It seems like some (or most) of the existing contribution guide is instructional for contributions toward accessibility issues outside this repo itself. I understand this is the purpose of this repo (to direct efforts to accessibility issues on other jupyter projects). Thinking to achieve this potentially through organization or maybe just an addition of "how to contribute to the jupyter/accessibility repo itself" vs to other jupyter repositories. 
     a. For contributions directed to "jupyter/accessibility", sounds
         communication via Github is preferred?
 

3. I noticed some instructions directing contributors to target the ci branch, but I don't see a ci branch. Has this been changed to something else?

4. I think the ARCHITECTURE.md file is in need of some updating too. If you could speak to the below thoughts that would be great...
- /ja11y the python module -> renamed to /pa11y-jupyter
- /packages the node packages -> seems that this directory was removed
- there is a mention of "3. accessibility testing tools" -> Not much else is said of it or where such tools can be found. I see some more mention in pa11y-jupyter/README.md, but wasn't sure about this since it seems to be within the python module folder. Perhaps they got combined.

5. Is there a significance of `jupyter` vs Jupyter Accessibility?
<img width="239" alt="image" src="https://user-images.githubusercontent.com/47162168/162091150-5bbb6e28-19fa-4150-9df7-5fc2f7c6d607.png">

I plan adjust the above for consistency.
<img width="239" alt="image" src="https://user-images.githubusercontent.com/47162168/162091892-1550fc14-cdb9-414a-b3f8-c521a35368c6.png">

6. From the Accessibility Goals Meeting Notes, “Notes are recorded publicly at [jupyter/accessibility](https://github.com/jupyter/accessibility).” where exactly? Here..(accessibility/docs/community/meeting-minutes/jupyterlab-accessibility-meetings/all-minutes.md)? Perhaps, can provide some clarity either in read the docs or on Meeting Notes page too.

7. Is there any documentation/information on how the read the docs page was setup from the generated jupyter book html files?

Thanks for the help!
- Brad

**Comment by isabela-pf** [comment] 2022-04-12 18:17
Thanks for numbering these, it makes it much easier to reply. In order:

1. Good observation! I think what I have in my head is to **a)** have a contribution guide specifically for this repo since there is work that can be done here, and **b)** have a statement that says something like “for contributions to other Jupyter projects, please refer to each projects’ contribution guide as needed.” It’s good to acknowledge that everyone in this ecosystem might work a little differently. These could be two different headers on the same document. So if it seems like that’s not what’s happening right now, I’d personally like it to be changed. Does that answer this question?

2. I have no idea. 😆My guess is that this was something that was planned, but no branch was actually made. I believe all CI infrastructure is not currently being run on this repo for now, so I’m not actually sure how relevant it is. @tonyfast is the one most familiar with what’s happening here. If he doesn’t have something to add, I think I’d encourage ignoring the CI wherever possible for now. I don’t want this to be a blocker for you, and we can always iterate on this once the CI situation is ironed out.

3. I wouldn’t be surprised if `ARCHITECTURE.md` describes a plan for the repo that isn’t all there yet. @tonyfast and @gabalafou are the ones who put this together, so they probably have the most knowledge as to whether this needs to be updated or if it is aspirational and needs to be left as-is. I don’t have any issues with any of your proposals in this section, but I’m also not the one who wrote the document.

To clarify, do you want to edit this document because it is support for contribution? My advice would be to have a PR to change each of these documents separately because it makes it easier for people to review and prevents one task from blocking the other. Of course, if there’s a reason these files should block one another, feel free to let me know and update them as one PR.

5. Nice catch! I think that was a styling choice by @tonyfast. Either is fine with me, but I agree I’d like the to be consistent regardless of what we choose.

6. Yep, that’s the correct file path! I recently merged something that was supposed to make these more findable on the docs site, but it doesn’t look like it’s working right. Feel free to make this more findable if you like. Once again, I’m happy to review this as it’s own PR if that’s easy so that it isn’t blocked by any of your other work.

7. That’s once again @tonyfast’s work! I have not found any documentation on this myself, but perhaps I’m just missing it.

Thank you for all the good questions!

**Comment by pws1453** [comment] 2022-04-13 17:45
Hello! We have created an initial PR for the contribution guide here: https://github.com/jupyter/accessibility/pull/82
Please leave any feedback you have for us over there.

**Closed** 2022-08-16 11:53 UTC
Labels: status: work in progress 🏗, area: community 🌱
